## YAML Template.
name: MCdisplay
main: display.Display
version: 0.3.3
api-version: 1.16
author: M0rica
website: https://github.com/M0rica/MCdisplay
commands:
    display:
        description:
        usage: "Usage: /display [on/off/image/video/replay/pause/stop]"
