## YAML Template.
name: MCdisplay
main: mcdisplay.MCDisplay
version: 1.0-alpha_1
api-version: 1.17
author: M0rica
website: https://github.com/M0rica/MCdisplay
commands:
    display:
        description:
        usage: "Usage: /display [on/off/image/video/replay/pause/stop/colormap]"